name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          libsqlite3-dev \
          libreadline-dev \
          libbz2-dev \
          libncurses5-dev \
          libgdbm-dev \
          liblzma-dev \
          zlib1g-dev \
          libjpeg-dev \
          libfreetype6-dev \
          liblcms2-dev \
          libopenjp2-7-dev \
          libtiff5-dev \
          tk-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libxcb1-dev
    
    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools android-sdk/cmdline-tools/latest
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_ENV
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
    
    - name: Install Buildozer
      run: |
        pip install buildozer cython
    
    - name: Build APK
      run: |
        cd "216 github"
        buildozer android debug
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: TaikoMini-APK-${{ github.run_number }}
        path: "216 github/bin/*.apk"
    
    - name: Create Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: "216 github/bin/*.apk"
        draft: false
        prerelease: false
